apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-profile
  name: mongodb-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-profile
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-profile
    spec:
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-profile-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 750m
            limits:
              cpu: 1500m
          volumeMounts:
            - mountPath: /data/db
              name: profile
        - image: divyanshus/copper:latest
          name: sidecar-bridge
          env:
          - name: RUST_LOG
            value: trace
          volumeMounts:
          - name: socks
            mountPath: /socks
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
                SYS_ADMIN
          command: ["ebpf-bridge"]
          args: ["driver", "--config", "/configs/ebpf-bridge-config.yaml"]
        - image: divyanshus/copper:latest
          name: sidecar
          env:
          - name: RUST_LOG
            value: trace
          volumeMounts:
          - name: socks
            mountPath: /socks
          command: ["dyn-proxy"]
          args: ["run", "--config", "/configs/proxy-config.yaml"]
      hostname: profile-db
      restartPolicy: Always
      volumes:
        - name: profile
          persistentVolumeClaim:
            claimName: profile-pvc
        - name: socks
          emptyDir: {}
status: {}
