---
# Source: social-network/charts/nginx-thrift/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-thrift
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 32000
  selector:
    service: nginx-thrift
