---
# Source: social-network/charts/media-memcached/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: media-memcached
  name: media-memcached
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: media-memcached
  template:
    metadata:
      labels:
        service: media-memcached
        app: media-memcached
    spec:
      containers:
      - name: "media-memcached"
        image: docker.io/library/memcached:1.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11211        
        volumeMounts:
        - name: media-memcached-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: media-memcached-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: media-memcached-config
        configMap:
          name: media-memcached
      hostname: media-memcached
      restartPolicy: Always
