---
# Source: social-network/charts/user-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-mongodb
  name: user-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: user-mongodb
  template:
    metadata:
      labels:
        service: user-mongodb
        app: user-mongodb
    spec:
      containers:
      - name: "user-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        args:
        - --config
        - /social-network-microservices/config/mongod.conf        
        volumeMounts:
        - name: user-mongodb-config
          mountPath: /social-network-microservices/config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: user-mongodb-config
        configMap:
          name: user-mongodb
      hostname: user-mongodb
      restartPolicy: Always
